version: '3'
services:
  db:
    image: postgres:12.5
    environment:
      POSTGRES_USER: bbbanalytics
      POSTGRES_PASSWORD: bbbanalytics
    ports:
      - "5432:5432"
  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://bbbanalytics:bbbanalytics@db:5432/bbbanalytics
      HOSTNAME: localhost
      JWT_SECURITY_SALT: SecretThatShouldChangedInProduction
    ports:
      - "8100:8100"
      - "9229:9229"
    volumes:
      - .:/app
    restart: on-failure
